spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:mysql://localhost:3306/Udon
    username: root
    password: kang0525@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    open-in-view: false

server:
  port: ${SERVER_PORT:8080}

feign:
  actionKey: ce1Xt98RxWbgebuHIYVtCG4IPkRZ2BmKv0eHXGpU%2FJv0JkJDyFs%2ByGzYULQQEOnQ01JERyyeTZr%2BRmHNgQT8zQ%3D%3D
  shelterKey: ce1Xt98RxWbgebuHIYVtCG4IPkRZ2BmKv0eHXGpU/Jv0JkJDyFs+yGzYULQQEOnQ01JERyyeTZr+RmHNgQT8zQ==

