spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/Udon}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    open-in-view: false

server:
  port: ${SERVER_PORT:8080}

feign:
  actionKey: ${ACTION_KEY}
  shelterKey: ${SHELTER_KEY}
  client:
    config:
      default:
        connect-timeout: 160000000
        read-timeout: 160000000

